JUnit version 4.13.1
.E....E.
Time: 4.854
There were 2 failures:
1) testDefaultDomainInParallel(com.dianping.cat.message.context.MessageIdFactoryTest)
java.lang.AssertionError: Not all threads completed in time. expected:<123400> but was:<49450>
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:784)
	at java.lang.Throwable.<init>(Throwable.java:266)
	at java.lang.Error.<init>(Error.java:70)
	at java.lang.AssertionError.<init>(AssertionError.java:58)
	at java.lang.AssertionError.<init>(AssertionError.java:74)
	at org.junit.Assert.fail$$PHOSPHORTAGGED(Assert.java:89)
	at org.junit.Assert.failNotEquals$$PHOSPHORTAGGED(Assert.java:835)
	at org.junit.Assert.assertEquals$$PHOSPHORTAGGED(Assert.java:647)
	at com.dianping.cat.message.context.MessageIdFactoryTest.testDefaultDomainInParallel$$PHOSPHORTAGGED(MessageIdFactoryTest.java:108)
2) testGivenDomainInParallel(com.dianping.cat.message.context.MessageIdFactoryTest)
java.lang.AssertionError: Not all threads completed in time. expected:<123400> but was:<50450>
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
	at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:784)
	at java.lang.Throwable.<init>(Throwable.java:266)
	at java.lang.Error.<init>(Error.java:70)
	at java.lang.AssertionError.<init>(AssertionError.java:58)
	at java.lang.AssertionError.<init>(AssertionError.java:74)
	at org.junit.Assert.fail$$PHOSPHORTAGGED(Assert.java:89)
	at org.junit.Assert.failNotEquals$$PHOSPHORTAGGED(Assert.java:835)
	at org.junit.Assert.assertEquals$$PHOSPHORTAGGED(Assert.java:647)
	at com.dianping.cat.message.context.MessageIdFactoryTest.testGivenDomainInParallel$$PHOSPHORTAGGED(MessageIdFactoryTest.java:141)

FAILURES!!!
Tests run: 6,  Failures: 2

