[TIME]: 0:00:02.904811
Randoop for Java version "4.3.2, local changes, branch master, commit df17bc8, 2023-01-08".
Cannot instantiate non-accessible class io.vertx.spi.cluster.consul.impl.ConsulEntry specified via --testclass or --classlist.
Cannot instantiate non-accessible class io.vertx.spi.cluster.consul.impl.ConversationUtils specified via --testclass or --classlist.

Will try to generate tests for 10 out of 12 classes.
PUBLIC MEMBERS=98
Explorer = ForwardGenerator(steps: 0, null steps: 0, num_sequences_generated: 0;
    allSequences: 0, regresson seqs: 0, error seqs: 0=0=0, invalid seqs: 0, subsumed_sequences: 0, num_failed_output_test: 0;
    sideEffectFreeMethods: 1115, runtimePrimitivesSeen: 38)

Progress update: steps=1, test inputs generated=0, failing inputs=0      (2023-11-20T09:10:10.569Z     18.2M used)createAndClassifySequences threw an exception
java.lang.NullPointerException
	at io.vertx.spi.cluster.consul.impl.ConsulMap.plainEntries(ConsulMap.java:247)
	at io.vertx.spi.cluster.consul.impl.ConsulMap.entries(ConsulMap.java:157)
	at io.vertx.spi.cluster.consul.impl.ConsulSyncMap.entrySet(ConsulSyncMap.java:117)
	at randoop.org.plumelib.util.StringsPlume.mapToStringAndClass(StringsPlume.java:1176)
	at randoop.org.plumelib.util.StringsPlume.toStringAndClass(StringsPlume.java:1059)
	at randoop.org.plumelib.util.StringsPlume.toStringAndClass(StringsPlume.java:1033)
	at randoop.operation.MethodCall.execute(MethodCall.java:170)
	at randoop.operation.TypedOperation.execute(TypedOperation.java:310)
	at randoop.sequence.Statement.execute(Statement.java:163)
	at randoop.sequence.ExecutableSequence.executeStatement(ExecutableSequence.java:416)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:308)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:237)
	at randoop.generation.ForwardGenerator.step(ForwardGenerator.java:237)
	at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:321)
	at randoop.main.GenTests.handle(GenTests.java:515)
	at randoop.main.Main.nonStaticMain(Main.java:69)
	at randoop.main.Main.main(Main.java:31)


Throwable thrown while handling command: java.lang.NullPointerException
java.lang.NullPointerException
	at io.vertx.spi.cluster.consul.impl.ConsulMap.plainEntries(ConsulMap.java:247)
	at io.vertx.spi.cluster.consul.impl.ConsulMap.entries(ConsulMap.java:157)
	at io.vertx.spi.cluster.consul.impl.ConsulSyncMap.entrySet(ConsulSyncMap.java:117)
	at randoop.org.plumelib.util.StringsPlume.mapToStringAndClass(StringsPlume.java:1176)
	at randoop.org.plumelib.util.StringsPlume.toStringAndClass(StringsPlume.java:1059)
	at randoop.org.plumelib.util.StringsPlume.toStringAndClass(StringsPlume.java:1033)
	at randoop.operation.MethodCall.execute(MethodCall.java:170)
	at randoop.operation.TypedOperation.execute(TypedOperation.java:310)
	at randoop.sequence.Statement.execute(Statement.java:163)
	at randoop.sequence.ExecutableSequence.executeStatement(ExecutableSequence.java:416)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:308)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:237)
	at randoop.generation.ForwardGenerator.step(ForwardGenerator.java:237)
	at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:321)
	at randoop.main.GenTests.handle(GenTests.java:515)
	at randoop.main.Main.nonStaticMain(Main.java:69)
	at randoop.main.Main.main(Main.java:31)

Randoop failed.
Last sequence under execution: 
io.vertx.spi.cluster.consul.impl.ClusterManagerInternalContext clusterManagerInternalContext1 = new io.vertx.spi.cluster.consul.impl.ClusterManagerInternalContext();
io.vertx.spi.cluster.consul.impl.ConsulSyncMap<java.lang.CharSequence,io.vertx.spi.cluster.consul.impl.ClusterManagerInternalContext> charSequenceMap2 = new io.vertx.spi.cluster.consul.impl.ConsulSyncMap<java.lang.CharSequence,io.vertx.spi.cluster.consul.impl.ClusterManagerInternalContext>("", clusterManagerInternalContext1);
io.vertx.spi.cluster.consul.impl.ClusterManagerInternalContext clusterManagerInternalContext4 = new io.vertx.spi.cluster.consul.impl.ClusterManagerInternalContext();
io.vertx.spi.cluster.consul.impl.ConsulSyncMap<java.lang.CharSequence,io.vertx.spi.cluster.consul.impl.ClusterManagerInternalContext> charSequenceMap5 = new io.vertx.spi.cluster.consul.impl.ConsulSyncMap<java.lang.CharSequence,io.vertx.spi.cluster.consul.impl.ClusterManagerInternalContext>("", clusterManagerInternalContext4);
charSequenceMap2.putAll((java.util.Map<java.lang.CharSequence,io.vertx.spi.cluster.consul.impl.ClusterManagerInternalContext>)charSequenceMap5);
